### PR TITLE
Remove parameter reading from environment

### PR DESCRIPTION
**Pull request by gondzo**
Removed reading parameters from environment and removed all config files
Added reading config parameters from options parameter in jwtAuthenticator
Replaced request(...) with request.post(...)

@sachin-maheshwari After merging, we can tag this with v2.4 so it can be referenced from other projects
FYI @mtwomey

### CODE REVIEW

**Comment by sachin-maheshwari** [comment]
@gondzo, I'll check this. Thanks!.

**Comment by sachin-maheshwari** [comment]
@gondzo as verifying unit test cases, getting error. Please fix.

**Comment by gondzo** [comment]
That is not related to this task IMO, tests are broken in dev too

**Comment by sachin-maheshwari** [comment]
@gondzo k..

**Pull request merged**
